spring:
  application:
    name: WELCOME-API-TEST
  boot:
    admin:
      client:
        url: http://localhost:1111/
        

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  msg: This is Welcome API.
